### ISSUE TITLE
No Args Crash

### ISSUE THREAD

**Issue by mazeemkalhoro** [smaugho/declex#80]
I have created a demo project (_declexdemo_) and calling service using @ServerModel in TypeModel, after getting response from server, it is getting crash. any idea?

`FATAL EXCEPTION: pool-2-thread-1
                                                                      Process: com.azeem.declexdemo, PID: 25856
                                                                      java.lang.RuntimeException: Failed to invoke public com.azeem.declexdemo.TypeModel_() with no args
                                                                          at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:116)
                                                                          at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
                                                                          at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
                                                                          at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
                                                                          at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
                                                                          at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                          at com.google.gson.Gson.fromJson(Gson.java:952)
                                                                          at com.azeem.declexdemo.TypeModel_.getServerModels(TypeModel_.java:443)
                                                                          at com.azeem.declexdemo.TypeModel_.getModelList_(TypeModel_.java:232)
                                                                          at com.azeem.declexdemo.MainActivity_$1.execute(MainActivity_.java:91)
                                                                          at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:403)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.activeandroid.TableInfo com.activeandroid.ModelInfo.getTableInfo(java.lang.Class)' on a null object reference
                                                                          at com.activeandroid.Cache.getTableInfo(Cache.java:148)
                                                                          at com.activeandroid.Model.<init>(Model.java:54)
                                                                          at com.azeem.declexdemo.TypeModel.<init>(TypeModel.java:18)
                                                                          at com.azeem.declexdemo.TypeModel_.<init>(TypeModel_.java:61)
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                          at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
                                                                          at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) 
                                                                          at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
                                                                          at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
                                                                          at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
                                                                          at com.google.gson.Gson.fromJson(Gson.java:887) 
                                                                          at com.google.gson.Gson.fromJson(Gson.java:952) 
                                                                          at com.azeem.declexdemo.TypeModel_.getServerModels(TypeModel_.java:443) 
                                                                          at com.azeem.declexdemo.TypeModel_.getModelList_(TypeModel_.java:232) 
                                                                          at com.azeem.declexdemo.MainActivity_$1.execute(MainActivity_.java:91) 
                                                                          at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:403) 
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818)`

**Comment by smaugho** [comment]
Could you please provide the Code of your TypeModel?. It seams an error when downloading the Model from the server and parsing with GSon... Is your server returning a valid JSON object?

**Comment by smaugho** [comment]
Issue was not provided correctly.
